export const refs = {
  body: document.querySelector('body'),
  toggleTheme: document.querySelector('.toggle-theme'),
  wraper: document.querySelector('.wraper'),
  content: document.querySelector('.content'),
  footer: document.querySelector('.footer_box'),
  modal_bgr: document.querySelector('.film-modal-content'),
  form: document.querySelector('.header__search-form'),
  gallery: document.querySelector('.container-films'),
  listEl: document.querySelector('.pagination__list'),
  spinner: document.querySelector('.loader'),
  form: document.querySelector('.header__search-form'),
  gallery: document.querySelector('.container-films'),
  pagination: document.querySelector('.pagination'),
  listEl: document.querySelector('.pagination__list'),
  iconSun: document.querySelector('.icon-sun'),
  iconBrightness: document.querySelector('.icon-brightness'),
  headerNavList: document.querySelector('.header__nav-list'),
  queueBtnInLibrary: document.querySelector('.header__mylibrary-btn--que'),
  watchedBtnInLibrary: document.querySelector('.watched-js'),
  homeBtn: document.querySelector('.home-js'),
  sectionHeader: document.querySelector('.header__section'),
  libraryButtons: document.querySelector('.header__mylibrary'),
  toggleTheme: document.querySelector('.toggle-theme'),
  modalFooter: document.querySelector('.modal-footer__box'),
  collection: document.querySelector(`.container-films`),
  btnUp: document.querySelector('.btnUp'),
  parallaxImg: document.querySelector('.parallax-img'),
};


