export const refs = {
  body: document.querySelector('body'),
  toggleTheme: document.querySelector('.toggle-theme'),
  footer: document.querySelector('.footer_box'),
  modal_bgr: document.querySelector('.film-modal-content'),
  form: document.querySelector('.header__search-form'),
  gallery: document.querySelector('.container-films'),
  listEl: document.querySelector('.pagination__list'),
  spinner: document.querySelector('.loader'),
  form: document.querySelector('.header__search-form'),
  gallery: document.querySelector('.container-films'),
  pagination: document.querySelector('.pagination'),
  listEl: document.querySelector('.pagination__list'),
  iconSun: document.querySelector('.icon-sun'),
  iconBrightness: document.querySelector('.icon-brightness'),
  headerNavList: document.querySelector('.header__nav-list'),
  queueBtnInLibrary: document.querySelector('.header__mylibrary-btn--que'),
  watchedBtnInLibrary: document.querySelector('.watched-js'),
  homeBtn: document.querySelector('.home-js'),
  sectionHeader: document.querySelector('.header__section'),
  libraryButtons: document.querySelector('.header__mylibrary'),
  toggleTheme: document.querySelector('.toggle-theme'),
  modalFooter: document.querySelector('.modal-footer__box'),
  collection: document.querySelector(`.container-films`),
  container: document.querySelector('.container-films'),
  btnUp: document.querySelector('.btnUp'),
  homeButton: document.querySelector('.home-js--button'),
  myLibraryButton: document.querySelector('.my-library-js--button'),
  myLibraryBtn: document.querySelector('.my-library-js'),
  watchedAddBtn: document.querySelector('.watched-add'),
  homeActive: document.querySelector('.home-js'),
  queueAddBtn: document.querySelector('.queue-add'),
  removeBtn: document.querySelector('.remove-from-queue'),
  removeFromQueueBtn: document.querySelector('.remove-from-queue'),
  modal: document.querySelector('.film-modal-content'),
  containerModal: document.querySelector('.backdrop-details'),
  modalClose: document.querySelector('.modal-icon-cross'),
  libraryButtons: document.querySelector('.header__mylibrary'),
  filterButtons: document.querySelector('.filter'),
  sortButton: document.querySelector('button[name=sort]'),
  genreButton: document.querySelector('button[name=genre]'),
  yearButton: document.querySelector('button[name=year]'),

  //FIREBASE//
  //header auth btns
  signinBtn: document.querySelector('.signin-Btn'),
  loginBtn: document.querySelector('.login-Btn'),
  //submit form btns
  logOut: document.querySelector('.login-Out'),
  submitSignBtn: document.querySelector('.submit-signUp-btn'),
  submitLoginBtn: document.querySelector('.submit-login-btn'),

  //checkConnection
  sectionMain: document.querySelector('.section-main'),
  errorImg: document.querySelector('.error-img'),
};
